const theme = require('tailwindcss/defaultTheme')
const formPlugin = require('@tailwindcss/forms')
const animatePlugin = require('tailwindcss-animate')

export default {
    content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
    theme: {
        extend: {
            fontFamily: {
                ...theme.fontFamily,
                sans: ['Inter', ...theme.fontFamily.serif],
            },
            spacing: {
                [6.5]: '1.625rem',
            },
            colors: {
                mint: {
                    green: '#44AEC3',
                    dark: '#44AEC3',
                },
                primary: {
                    50: '#EBF5FF',
                    100: '#E1EFFE',
                    200: '#C3DDFD',
                    300: '#A4CAFE',
                    400: '#76A9FA',
                    500: '#3F83F8',
                    600: '#1C64F2',
                    700: '#1A56DB',
                    800: '#1E429F',
                    900: '#233876',
                },
                gray: {
                    50: '#F9FAFB',
                    100: '#F3F4F6',
                    200: '#E5E7EB',
                    300: '#D1D5DB',
                    400: '#9CA3AF',
                    500: '#6B7280',
                    600: '#4B5563',
                    700: '#374151',
                    800: '#1F2A37',
                    900: '#111928',
                    text: '#6A6A6A',
                },
                blue: {
                    50: '#EBF5FF',
                    100: '#E1EFFE',
                    200: '#C3DDFD',
                    300: '#A4CAFE',
                    400: '#76A9FA',
                    500: '#3F83F8',
                    600: '#1C64F2',
                    700: '#1A56DB',
                    800: '#1E429F',
                    900: '#233876',
                },
                red: {
                    50: '#FDF2F2',
                    100: '#FDE8E8',
                    200: '#FBD5D5',
                    300: '#F8B4B4',
                    400: '#F98080',
                    500: '#F05252',
                    600: '#E02424',
                    700: '#C81E1E',
                    800: '#9B1C1C',
                    900: '#771D1D',
                },
                orange: {
                    50: '',
                    100: '',
                    200: '',
                    300: '',
                    400: '',
                    500: '',
                    600: '',
                    700: '',
                    800: '',
                    900: '',
                },
                yellow: {
                    50: '',
                    100: '',
                    200: '',
                    300: '',
                    400: '',
                    500: '',
                    600: '',
                    700: '',
                    800: '',
                    900: '',
                },
                green: {
                    50: '',
                    100: '#DEF7EC',
                    200: '',
                    300: '',
                    400: '',
                    500: '',
                    600: '',
                    700: '#046C4E',
                    800: '',
                    900: '',
                },
                teal: {
                    50: '',
                    100: '',
                    200: '',
                    300: '',
                    400: '',
                    500: '',
                    600: '',
                    700: '',
                    800: '',
                    900: '',
                },
                indigo: {
                    50: '',
                    100: '',
                    200: '',
                    300: '',
                    400: '',
                    500: '',
                    600: '',
                    700: '',
                    800: '',
                    900: '',
                },
                purple: {
                    50: '',
                    100: '',
                    200: '',
                    300: '',
                    400: '',
                    500: '',
                    600: '',
                    700: '',
                    800: '',
                    900: '',
                },
                pink: {
                    50: '',
                    100: '',
                    200: '',
                    300: '',
                    400: '',
                    500: '',
                    600: '',
                    700: '',
                    800: '',
                    900: '',
                },
            },
        },
    },
    plugins: [formPlugin, animatePlugin],
}
